trigger:
  branches:
    include:
      - Master   # Trigger on main branch changes

stages:
# -------------------
# CI Stage - Validate ARM Template
# -------------------
- stage: CI
  displayName: "Validate ADF ARM Template"
  jobs:
    - job: Validate
      displayName: "Validate ARM Template"
      pool:
        vmImage: 'windows-latest'
      steps:
        - checkout: self

        # Pre-deployment script
        #- task: PowerShell@2
          #displayName: "Run Pre-Deployment Script"
          #inputs:
            #targetType: 'filePath'
            #filePath: 'Script/pre-deploy.ps1'
            #arguments: "-TeamsWebhookUrl $(TeamsWebhookUrl)"
        
        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '$(Build.Repository.LocalPath)/build/' #replace with the package.json folder
            verbose: true
          displayName: 'Install npm package'

        # Validate ARM template
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(Build.Repository.LocalPath)/build/' #replace with the package.json folder
            customCommand: 'run build validate $(Build.Repository.LocalPath)/adf_publish /subscriptions/8b0b2e24-f3b3-4196-82de-72c9592eae1d/resourceGroups/Primary_Group/providers/Microsoft.DataFactory/factories/Mah-Primary-ADF'
          displayName: 'Validate ARM template'

        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(Build.Repository.LocalPath)/build/' #replace with the package.json folder
            customCommand: 'run build export $(Build.Repository.LocalPath) /subscriptions/8b0b2e24-f3b3-4196-82de-72c9592eae1d/resourceGroups/Primary_Group/providers/Microsoft.DataFactory/factories/Mah-Primary-ADF "ArmTemplate"'
            #For using preview that allows you to only stop/ start triggers that are modified, please comment out the above line and uncomment the below line. Make sure the package.json contains the build-preview command. 
            #customCommand: 'run build-preview export $(Build.Repository.LocalPath) /subscriptions/aaaa0a0a-bb1b-cc2c-dd3d-eeeeee4e4e4e/resourceGroups/GartnerMQ2021/providers/Microsoft.DataFactory/factories/Dev-GartnerMQ2021-DataFactory "ArmTemplate"'
            verbose: true
          displayName: 'Validate and Generate ARM template'

          # Publish the artifact to be used as a source for a release pipeline.
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.Repository.LocalPath)/build/ArmTemplate' #replace with the package.json folder
            artifact: 'ArmTemplates'
            publishLocation: 'pipeline'

# -------------------
# CD Stage - Deploy to Primary ADF
# -------------------
- stage: CD
  displayName: "Deploy to Primary ADF"
  dependsOn: CI
  
  jobs:
    - deployment: DeployADF
      displayName: Deploy Primary ADF
      environment: "Toggle-Test"

      pool:
        vmImage: 'windows-latest'
      
      strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self

                  # Download Artifact
                  - task: DownloadPipelineArtifact@2
                    inputs:
                      artifact: 'ArmTemplates'
                      path: '$(Pipeline.Workspace)/ArmTemplates'

                  # Deployment
                  - task: AzureResourceManagerTemplateDeployment@3
                    displayName: "Deploy ARM Template"
                    inputs:
                      deploymentScope: 'Resource Group'
                      azureResourceManagerConnection: 'ADF-Connection'
                      subscriptionId: '8b0b2e24-f3b3-4196-82de-72c9592eae1d'
                      action: 'Create Or Update Resource Group'
                      resourceGroupName: 'Primary_Group'
                      location: 'Central India'
                      templateLocation: 'Linked artifact'
                      csmFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateForFactory.json'
                      csmParametersFile: '$(Pipeline.Workspace)/ArmTemplates/ARMTemplateParametersForFactory.json'
                      overrideParameters: '-factoryName Toggle-Test' 
                      delete_ADF_resources: $true
                      
                  # Post-deployment script
                  #- task: PowerShell@2
                    #displayName: "Run Post-Deployment Script"
                    #inputs:
                      #targetType: 'filePath'
                      #filePath: 'Script/post-deploy.ps1'
                      #arguments: "-TeamsWebhookUrl $(TeamsWebhookUrl) -EmailUser $(EmailUser) -EmailPassword $(EmailPassword)"
